[build]
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile"

[deploy]
startCommand = "bash /entrypoint-railway.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
